name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-xdist
    
    - name: Run unit tests
      run: |
        pytest backend/tests/unit --cov=backend --cov-report=xml
    
    - name: Run integration tests
      run: |
        pytest backend/tests/integration --cov=backend --cov-report=xml --cov-append
    
    - name: Run edge case tests
      run: |
        pytest backend/tests/test_edge_cases.py --cov=backend --cov-report=xml --cov-append
    
    - name: Run load tests
      run: |
        pytest backend/tests/test_load.py --cov=backend --cov-report=xml --cov-append
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
    
    - name: Check test coverage
      run: |
        coverage report --fail-under=80